hash-format = "sha256"

[[files]]
file = "config/promotedserver/servers.dat"

[[files]]
file = "mods/ChainStyleWither-1.7.0.jar"

[[files]]
file = "mods/apothicspawners-0.0.1.jar"

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/crossbow_scoping.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/grind-enchantments.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-overlays.pw.toml"
metafile = true

[[files]]
file = "mods/inline-tooltips.pw.toml"
metafile = true

[[files]]
file = "mods/instant-feedback.pw.toml"
metafile = true

[[files]]
file = "mods/laseredstone.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/promotedserver.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/x-bar-theory.pw.toml"
metafile = true
