name = "Fabric Holiday 25"
author = "Louis, Fabricord"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11-pre4", "1.21.11-rc1"]
no-internal-hashes = true
